import type { UmbrellaTool } from "./types";

/** Original shipped tools — merged with EXTRA_UMBRELLA_TOOLS in tools-config. */
export const CORE_UMBRELLA_TOOLS: UmbrellaTool[] = [
  {
    slug: "svg-generators",
    title: "SVG generators",
    description: "Browse SVG utilities: CSS background converter and shape divider generator — all client-side.",
    category: "css",
    icon: "◇",
    keywords: ["svg generators", "svg tools", "svg utilities"],
    seoTitle: "SVG generators — CSS backgrounds & section dividers online",
    seoDescription:
      "Free SVG tools in your browser: convert SVG to CSS backgrounds and generate wave or curve section dividers.",
  },
  {
    slug: "svg-to-css-background",
    title: "SVG → CSS background",
    description: "Turn inline SVG into a data URL and copy-ready background-image CSS.",
    category: "css",
    icon: "◈",
    keywords: ["svg to css", "svg to css converter", "background-image", "data url"],
    seoTitle: "SVG to CSS background-image — data URL generator online",
    seoDescription:
      "Convert inline SVG to a data URL and copy-ready background-image CSS. Free browser-based tool — no upload.",
  },
  {
    slug: "shape-divider-generator",
    title: "Shape divider generator",
    description: "Create SVG wave, curve, tilt, and zigzag dividers for sections — copy SVG or CSS.",
    category: "css",
    icon: "〰",
    keywords: ["shape divider", "svg wave divider", "section divider svg", "landing page divider"],
    seoTitle: "SVG shape divider generator — waves & curves for sections",
    seoDescription:
      "Generate decorative SVG section dividers with preset shapes. Export markup or CSS background-image — runs locally.",
  },
  {
    slug: "css-shadow-generator",
    title: "CSS box-shadow",
    description: "Live preview for offset, blur, spread, and color — copy the value in one click.",
    category: "css",
    icon: "◐",
    keywords: ["box-shadow generator", "css shadow"],
    seoTitle: "CSS box-shadow generator — live preview & copy CSS free",
  },
  {
    slug: "json-formatter",
    title: "JSON formatter",
    description: "Format, minify, and validate JSON — fix payloads before APIs or configs.",
    category: "json",
    icon: "{}",
    keywords: ["json formatter", "json minify", "json validator online"],
    seoTitle: "JSON formatter & validator — minify and prettify online free",
    seoDescription:
      "Format, minify, and validate JSON for APIs and configs. Free online JSON tool — everything runs in your browser, no account.",
  },
  {
    slug: "jwt-decoder",
    title: "JWT decoder",
    description: "Inspect header and payload (Base64URL). Read-only — does not verify signatures.",
    category: "json",
    icon: "◎",
    keywords: ["jwt decode", "jwt parser online", "json web token"],
    seoTitle: "JWT decoder online — inspect JSON Web Token header & payload",
  },
  {
    slug: "json-to-csv",
    title: "JSON → CSV",
    description: "Convert JSON arrays to CSV with instant preview and download.",
    category: "csv",
    icon: "▤",
    keywords: ["json to csv", "export csv"],
    seoTitle: "JSON to CSV converter — export arrays online free",
  },
  {
    slug: "base64",
    title: "Base64 encode / decode",
    description: "Encode or decode Base64 for UTF-8 text — handy for APIs, tokens, and debugging.",
    category: "base64",
    icon: "⊕",
    keywords: ["base64 encode", "base64 decode online", "utf-8 base64"],
    seoTitle: "Base64 encode & decode — UTF-8 text online free",
    seoDescription:
      "Encode or decode Base64 for UTF-8 text, tokens, and APIs. Free Base64 tool — runs entirely in your browser.",
  },
  {
    slug: "hash-generator",
    title: "SHA hash generator",
    description: "Compute SHA-256, SHA-384, or SHA-512 digests of any text — Web Crypto, client-side only.",
    category: "hash",
    icon: "#",
    keywords: ["sha256 online", "sha512 hash", "generate hash"],
    seoTitle: "SHA-256/384/512 hash generator — free online in browser",
    seoDescription:
      "Generate SHA-256, SHA-384, or SHA-512 hashes with Web Crypto. Free hash tool — your text never leaves this tab.",
  },
  {
    slug: "uuid-generator",
    title: "UUID generator",
    description: "Generate RFC 4122 v4 UUIDs with one click — copy individually or all at once.",
    category: "text",
    icon: "◇",
    keywords: ["uuid generator", "guid generator online", "random uuid"],
    seoTitle: "UUID generator — random v4 GUID online free",
  },
  {
    slug: "timestamp-converter",
    title: "Unix timestamp converter",
    description: "Convert Unix seconds or milliseconds ↔ ISO 8601 dates in local and UTC.",
    category: "text",
    icon: "◷",
    keywords: ["unix timestamp converter", "epoch converter", "iso 8601"],
    seoTitle: "Unix timestamp converter — epoch ↔ ISO 8601 date",
  },
  {
    slug: "url-encode",
    title: "URL encode / decode",
    description: "Percent-encode or decode query strings and path components safely in the browser.",
    category: "url",
    icon: "§",
    keywords: ["url encode", "percent encode", "decodeURIComponent"],
    seoTitle: "URL encode & decode — percent-encoding online free",
  },
  {
    slug: "database-url-parser",
    title: "Database URL parser",
    description:
      "Split PostgreSQL, MySQL, MongoDB, Redis, and other connection URLs into scheme, host, port, user, and database.",
    category: "database",
    icon: "▢",
    keywords: ["postgres connection string", "mysql url parser", "database url"],
    seoTitle: "Database URL parser — Postgres, MySQL, MongoDB, Redis",
  },
  {
    slug: "random-string",
    title: "Random string generator",
    description: "Generate cryptographically random strings — length, charset, and one-click copy.",
    category: "randomizers",
    icon: "✧",
    keywords: ["random string", "secure random", "token generator"],
    seoTitle: "Random string generator — secure tokens online free",
  },
  {
    slug: "base32-encode-decode",
    title: "Base32 encode / decode",
    description: "RFC 4648 Base32 for encoded identifiers, OTP secrets, and text-safe binary.",
    category: "base32",
    icon: "Ⓑ",
    keywords: ["base32 encode", "rfc 4648", "base32 decode"],
    seoTitle: "Base32 encoder & decoder — RFC 4648 online free",
  },
  {
    slug: "base58-encode-decode",
    title: "Base58 encode / decode",
    description: "Bitcoin-style Base58 — compact, avoids ambiguous characters (0, O, I, l).",
    category: "base58",
    icon: "₿",
    keywords: ["base58", "bitcoin encoding"],
    seoTitle: "Base58 encoder & decoder — Bitcoin-style online free",
  },
  {
    slug: "hmac-generator",
    title: "HMAC generator",
    description: "Compute HMAC-SHA-256/384/512 hex for a secret and message — useful for webhooks and APIs.",
    category: "hmac",
    icon: "⌬",
    keywords: ["hmac sha256", "hmac generator online", "webhook signature"],
    seoTitle: "HMAC generator — SHA-256/384/512 for webhooks & APIs",
  },
  {
    slug: "bcrypt-hash",
    title: "Bcrypt hash & compare",
    description: "Hash passwords with bcrypt or verify a password against a hash — runs locally in your browser.",
    category: "bcrypt",
    icon: "⚿",
    keywords: ["bcrypt online", "bcrypt compare", "password hash"],
    seoTitle: "Bcrypt hash & compare — online password tool free",
    seoDescription:
      "Hash or verify bcrypt passwords in your browser with bcryptjs. Free tool — passwords are not sent to our servers.",
  },
  {
    slug: "qr-code-generator",
    title: "QR code generator",
    description: "Turn any text or URL into a QR code — PNG data URL for download or embedding.",
    category: "qrcode",
    icon: "▣",
    keywords: ["qr code generator", "qr online"],
    seoTitle: "QR code generator — free PNG from text or URL online",
    seoDescription:
      "Create a QR code from any text or URL with a downloadable PNG. Free QR generator — runs locally in your browser.",
  },
  {
    slug: "cidr-calculator",
    title: "CIDR calculator",
    description: "IPv4 CIDR — network and broadcast addresses, subnet mask, and usable host range.",
    category: "network",
    icon: "⬚",
    keywords: ["cidr calculator", "subnet calculator", "ipv4 cidr"],
    seoTitle: "CIDR calculator — IPv4 subnet, mask & network range",
  },
  {
    slug: "checksum-calculator",
    title: "Checksum calculator",
    description: "IEEE CRC-32 and Fletcher-16 over UTF-8 bytes — compare with firmware, ZIP, and network stacks.",
    category: "checksum",
    icon: "∑",
    keywords: ["crc32 online", "checksum calculator", "fletcher checksum"],
    seoTitle: "CRC-32 checksum calculator — Fletcher-16 online free",
  },
  {
    slug: "pdf-merge",
    title: "PDF merge",
    description: "Combine multiple PDF files in order — download one merged document. Runs entirely in your browser.",
    category: "pdf",
    icon: "∪",
    keywords: ["merge pdf", "combine pdf online", "pdf merger"],
    seoTitle: "Merge PDF files online — combine PDFs free in your browser",
    seoDescription:
      "Merge two or more PDFs into one file with pdf-lib. Free client-side tool — your PDFs are not uploaded to our servers.",
  },
  {
    slug: "pdf-extract-pages",
    title: "PDF extract pages",
    description: "Keep only selected pages (ranges like 1-3, 5, 8) and download a new PDF — client-side only.",
    category: "pdf",
    icon: "⊡",
    keywords: ["extract pdf pages", "split pdf pages", "pdf page range"],
    seoTitle: "Extract PDF pages — save selected pages as a new PDF online",
    seoDescription:
      "Pick page ranges from a PDF and download a smaller file. Runs locally in your browser with pdf-lib.",
  },
  {
    slug: "code-playground",
    title: "Code playground",
    description:
      "Monaco IDE: run JavaScript, TypeScript, Python, Java, C++, Go in a remote sandbox; preview HTML locally. Shortcuts, console, starter templates.",
    category: "javascript",
    icon: "⌘",
    keywords: [
      "online ide",
      "run code online",
      "javascript playground",
      "python online",
      "monaco editor online",
      "typescript playground",
    ],
    seoTitle: "Online code playground — JS, TS, Python, Java, C++, Go & HTML preview",
    seoDescription:
      "Free browser IDE with Monaco: run JS, TS, Python, Java, C++, Go via Piston sandbox; HTML live preview. Console output, Cmd+Enter to run.",
  },
  {
    slug: "pastebin",
    title: "Pastebin",
    description:
      "Plain-text scratch pad with optional share link (base64 in the URL), clipboard copy, and .txt download — no server upload.",
    category: "pastebin",
    icon: "¶",
    keywords: ["pastebin online", "text share", "client side paste"],
    seoTitle: "Pastebin — share text via browser link",
  },
];
