import type { UmbrellaTool } from "./types";

/** Original shipped tools — merged with EXTRA_UMBRELLA_TOOLS in tools-config. */
export const CORE_UMBRELLA_TOOLS: UmbrellaTool[] = [
  {
    slug: "svg-to-css-background",
    title: "SVG → CSS background",
    description: "Turn inline SVG into a data URL and copy-ready background-image CSS.",
    category: "css",
    icon: "◈",
    keywords: ["svg to css", "background-image", "data url"],
  },
  {
    slug: "css-shadow-generator",
    title: "CSS box-shadow",
    description: "Live preview for offset, blur, spread, and color — copy the value in one click.",
    category: "css",
    icon: "◐",
    keywords: ["box-shadow generator", "css shadow"],
  },
  {
    slug: "json-formatter",
    title: "JSON formatter",
    description: "Format, minify, and validate JSON — fix payloads before APIs or configs.",
    category: "json",
    icon: "{}",
    keywords: ["json formatter", "json minify", "json validator online"],
  },
  {
    slug: "jwt-decoder",
    title: "JWT decoder",
    description: "Inspect header and payload (Base64URL). Read-only — does not verify signatures.",
    category: "json",
    icon: "◎",
    keywords: ["jwt decode", "jwt parser online", "json web token"],
  },
  {
    slug: "json-to-csv",
    title: "JSON → CSV",
    description: "Convert JSON arrays to CSV with instant preview and download.",
    category: "csv",
    icon: "▤",
    keywords: ["json to csv", "export csv"],
  },
  {
    slug: "base64",
    title: "Base64 encode / decode",
    description: "Encode or decode Base64 for UTF-8 text — handy for APIs, tokens, and debugging.",
    category: "base64",
    icon: "⊕",
    keywords: ["base64 encode", "base64 decode online", "utf-8 base64"],
  },
  {
    slug: "hash-generator",
    title: "SHA hash generator",
    description: "Compute SHA-256, SHA-384, or SHA-512 digests of any text — Web Crypto, client-side only.",
    category: "hash",
    icon: "#",
    keywords: ["sha256 online", "sha512 hash", "generate hash"],
  },
  {
    slug: "uuid-generator",
    title: "UUID generator",
    description: "Generate RFC 4122 v4 UUIDs with one click — copy individually or all at once.",
    category: "text",
    icon: "◇",
    keywords: ["uuid generator", "guid generator online", "random uuid"],
  },
  {
    slug: "timestamp-converter",
    title: "Unix timestamp converter",
    description: "Convert Unix seconds or milliseconds ↔ ISO 8601 dates in local and UTC.",
    category: "text",
    icon: "◷",
    keywords: ["unix timestamp converter", "epoch converter", "iso 8601"],
  },
  {
    slug: "url-encode",
    title: "URL encode / decode",
    description: "Percent-encode or decode query strings and path components safely in the browser.",
    category: "url",
    icon: "§",
    keywords: ["url encode", "percent encode", "decodeURIComponent"],
  },
  {
    slug: "database-url-parser",
    title: "Database URL parser",
    description:
      "Split PostgreSQL, MySQL, MongoDB, Redis, and other connection URLs into scheme, host, port, user, and database.",
    category: "database",
    icon: "▢",
    keywords: ["postgres connection string", "mysql url parser", "database url"],
  },
  {
    slug: "random-string",
    title: "Random string generator",
    description: "Generate cryptographically random strings — length, charset, and one-click copy.",
    category: "randomizers",
    icon: "✧",
    keywords: ["random string", "secure random", "token generator"],
  },
  {
    slug: "base32-encode-decode",
    title: "Base32 encode / decode",
    description: "RFC 4648 Base32 for encoded identifiers, OTP secrets, and text-safe binary.",
    category: "base32",
    icon: "Ⓑ",
    keywords: ["base32 encode", "rfc 4648", "base32 decode"],
  },
  {
    slug: "base58-encode-decode",
    title: "Base58 encode / decode",
    description: "Bitcoin-style Base58 — compact, avoids ambiguous characters (0, O, I, l).",
    category: "base58",
    icon: "₿",
    keywords: ["base58", "bitcoin encoding"],
  },
  {
    slug: "hmac-generator",
    title: "HMAC generator",
    description: "Compute HMAC-SHA-256/384/512 hex for a secret and message — useful for webhooks and APIs.",
    category: "hmac",
    icon: "⌬",
    keywords: ["hmac sha256", "hmac generator online", "webhook signature"],
  },
  {
    slug: "bcrypt-hash",
    title: "Bcrypt hash & compare",
    description: "Hash passwords with bcrypt or verify a password against a hash — runs locally in your browser.",
    category: "bcrypt",
    icon: "⚿",
    keywords: ["bcrypt online", "bcrypt compare", "password hash"],
  },
  {
    slug: "qr-code-generator",
    title: "QR code generator",
    description: "Turn any text or URL into a QR code — PNG data URL for download or embedding.",
    category: "qrcode",
    icon: "▣",
    keywords: ["qr code generator", "qr online"],
  },
  {
    slug: "cidr-calculator",
    title: "CIDR calculator",
    description: "IPv4 CIDR — network and broadcast addresses, subnet mask, and usable host range.",
    category: "network",
    icon: "⬚",
    keywords: ["cidr calculator", "subnet calculator", "ipv4 cidr"],
  },
  {
    slug: "checksum-calculator",
    title: "Checksum calculator",
    description: "IEEE CRC-32 and Fletcher-16 over UTF-8 bytes — compare with firmware, ZIP, and network stacks.",
    category: "checksum",
    icon: "∑",
    keywords: ["crc32 online", "checksum calculator", "fletcher checksum"],
  },
  {
    slug: "pastebin",
    title: "Pastebin",
    description:
      "Plain-text scratch pad with optional share link (base64 in the URL), clipboard copy, and .txt download — no server upload.",
    category: "pastebin",
    icon: "¶",
    keywords: ["pastebin online", "text share", "client side paste"],
  },
];
