import type { UmbrellaTool } from "./types";

/** Auto-generated — additional catalog tools. Merged into UMBRELLA_TOOLS in tools-config. */
export const EXTRA_UMBRELLA_TOOLS: UmbrellaTool[] = [
  {
    slug: "word-counter",
    title: "Word counter",
    description: "Count words, characters, and lines as you type — Unicode-aware.",
    category: "text",
    icon: "W",
  },
  {
    slug: "case-converter",
    title: "Case converter",
    description: "lower, UPPER, camelCase, PascalCase, snake_case, CONSTANT_CASE, Train-Case.",
    category: "text",
    icon: "Aa",
  },
  {
    slug: "line-sorter",
    title: "Line sorter",
    description: "Sort, reverse, shuffle lines; optional line numbers — all client-side.",
    category: "text",
    icon: "↕",
  },
  {
    slug: "whitespace-remover",
    title: "Whitespace remover",
    description: "Trim lines, collapse spaces, or strip all whitespace.",
    category: "text",
    icon: "␣",
  },
  {
    slug: "lorem-ipsum-generator",
    title: "Lorem ipsum generator",
    description: "Generate placeholder paragraphs with adjustable length.",
    category: "text",
    icon: "L",
  },
  {
    slug: "text-to-hex",
    title: "Text to HEX",
    description: "UTF-8 bytes to space-delimited hex.",
    category: "text",
    icon: "₀x",
  },
  {
    slug: "hex-to-text",
    title: "HEX to text",
    description: "Decode hex (with or without separators) back to UTF-8 text.",
    category: "text",
    icon: "x₀",
  },
  {
    slug: "url-parser",
    title: "URL parser",
    description: "Inspect scheme, host, path, query, and hash with the URL API.",
    category: "url",
    icon: "⊶",
  },
  {
    slug: "url-encoder",
    title: "URL encoder",
    description: "Percent-encode text for safe use in URLs and query strings.",
    category: "url",
    icon: "%",
  },
  {
    slug: "url-decoder",
    title: "URL decoder",
    description: "Decode percent-encoded strings to readable text.",
    category: "url",
    icon: "‰",
  },
  {
    slug: "slug-generator",
    title: "Slug generator",
    description: "SEO-friendly URL slugs from titles — lowercase, hyphenated.",
    category: "url",
    icon: "─",
  },
  {
    slug: "html-formatter",
    title: "HTML formatter",
    description: "Pretty-print HTML with js-beautify for readability.",
    category: "html",
    icon: "</>",
  },
  {
    slug: "html-minifier",
    title: "HTML minifier",
    description: "Remove extra whitespace and shrink HTML for production.",
    category: "html",
    icon: "⟨⟩",
  },
  {
    slug: "html-encoder",
    title: "HTML encoder",
    description: "Encode text to numeric / named HTML entities.",
    category: "html",
    icon: "&",
  },
  {
    slug: "html-decoder",
    title: "HTML decoder",
    description: "Decode HTML entities back to characters.",
    category: "html",
    icon: "&&",
  },
  {
    slug: "html-escape",
    title: "HTML escape",
    description: "Escape &, <, >, quotes for safe embedding in HTML.",
    category: "html",
    icon: "\\",
  },
  {
    slug: "html-unescape",
    title: "HTML unescape",
    description: "Unescape common HTML entities.",
    category: "html",
    icon: "∽",
  },
  {
    slug: "html-validator",
    title: "HTML validator",
    description: "Well-formedness check (DOMParser) — not a full W3C nu validator.",
    category: "html",
    icon: "✓",
  },
  {
    slug: "html-stripper",
    title: "HTML stripper",
    description: "Remove tags and keep text (best-effort).",
    category: "html",
    icon: "⌫",
  },
  {
    slug: "markdown-editor",
    title: "Markdown editor",
    description: "Edit Markdown with a live HTML preview (marked).",
    category: "markdown",
    icon: "M↓",
  },
  {
    slug: "markdown-to-html",
    title: "Markdown to HTML",
    description: "Convert Markdown to HTML in the browser.",
    category: "markdown",
    icon: "→",
  },
  {
    slug: "html-to-markdown",
    title: "HTML to Markdown",
    description: "Convert HTML to Markdown (turndown).",
    category: "markdown",
    icon: "←",
  },
  {
    slug: "css-beautifier",
    title: "CSS beautifier",
    description: "Pretty-print CSS stylesheets.",
    category: "css",
    icon: "{}",
  },
  {
    slug: "css-minifier",
    title: "CSS minifier",
    description: "Minify CSS with clean-css.",
    category: "css",
    icon: "{·}",
  },
  {
    slug: "css-validator",
    title: "CSS validator",
    description: "Basic brace/bracket balance and structure hints — not full W3C.",
    category: "css",
    icon: "✓",
  },
  {
    slug: "js-beautifier",
    title: "JavaScript beautifier",
    description: "Pretty-print JavaScript with js-beautify.",
    category: "javascript",
    icon: "JS",
  },
  {
    slug: "js-minifier",
    title: "JavaScript minifier",
    description: "Minify JS with terser (may fail on invalid syntax).",
    category: "javascript",
    icon: "js",
  },
  {
    slug: "js-escape",
    title: "JavaScript escape",
    description: "Escape a string for use inside JavaScript quotes.",
    category: "javascript",
    icon: "⧵",
  },
  {
    slug: "js-unescape",
    title: "JavaScript unescape",
    description: "Unescape JavaScript string escapes.",
    category: "javascript",
    icon: "⧹",
  },
  {
    slug: "json-minifier",
    title: "JSON minifier",
    description: "Remove whitespace from JSON — compact one-liner.",
    category: "json",
    icon: "{}",
  },
  {
    slug: "json-escape",
    title: "JSON escape",
    description: "Escape a string for embedding in JSON.",
    category: "json",
    icon: "\\",
  },
  {
    slug: "json-unescape",
    title: "JSON unescape",
    description: "Unescape JSON string escapes.",
    category: "json",
    icon: "∽",
  },
  {
    slug: "json-validator-standalone",
    title: "JSON validator",
    description: "Validate JSON and show parse errors with position.",
    category: "json",
    icon: "✓",
  },
  {
    slug: "xml-formatter",
    title: "XML formatter",
    description: "Pretty-print XML with indentation.",
    category: "xml",
    icon: "<>",
  },
  {
    slug: "xml-minifier",
    title: "XML minifier",
    description: "Collapse whitespace in XML.",
    category: "xml",
    icon: "⟨⟩",
  },
  {
    slug: "xml-encoder",
    title: "XML encoder",
    description: "Encode special characters for XML text nodes.",
    category: "xml",
    icon: "&",
  },
  {
    slug: "xml-decoder",
    title: "XML decoder",
    description: "Decode XML entities.",
    category: "xml",
    icon: "∽",
  },
  {
    slug: "xml-escape",
    title: "XML escape",
    description: "Escape &, <, >, quotes for XML.",
    category: "xml",
    icon: "\\",
  },
  {
    slug: "xml-unescape",
    title: "XML unescape",
    description: "Unescape XML entities.",
    category: "xml",
    icon: "∽",
  },
  {
    slug: "xml-validator",
    title: "XML validator",
    description: "Parse XML and report errors (DOMParser).",
    category: "xml",
    icon: "✓",
  },
  {
    slug: "xml-to-json",
    title: "XML to JSON",
    description: "Convert XML to JSON (fast-xml-parser).",
    category: "xml",
    icon: "⇒",
  },
  {
    slug: "json-to-xml",
    title: "JSON to XML",
    description: "Convert JSON to a simple XML document.",
    category: "xml",
    icon: "⇐",
  },
  {
    slug: "yaml-validator",
    title: "YAML validator",
    description: "Parse YAML and report errors (yaml package).",
    category: "yaml",
    icon: "✓",
  },
  {
    slug: "yaml-to-json",
    title: "YAML to JSON",
    description: "Convert YAML to formatted JSON.",
    category: "yaml",
    icon: "⇒",
  },
  {
    slug: "json-to-yaml",
    title: "JSON to YAML",
    description: "Convert JSON to YAML.",
    category: "yaml",
    icon: "⇐",
  },
  {
    slug: "csv-to-json",
    title: "CSV to JSON",
    description: "Parse CSV to JSON arrays with Papa Parse.",
    category: "csv",
    icon: "⇒",
  },
  {
    slug: "php-array-to-json",
    title: "PHP array to JSON",
    description: "Paste a PHP array literal — best-effort convert to JSON.",
    category: "php",
    icon: "⇒",
  },
  {
    slug: "json-to-php-array",
    title: "JSON to PHP array",
    description: "Convert JSON to a PHP array string.",
    category: "php",
    icon: "⇐",
  },
  {
    slug: "sql-formatter",
    title: "SQL formatter",
    description: "Pretty-print SQL with sql-formatter.",
    category: "database",
    icon: "§",
  },
  {
    slug: "sql-minifier",
    title: "SQL minifier",
    description: "Strip SQL comments and collapse whitespace.",
    category: "database",
    icon: "§·",
  },
  {
    slug: "sql-escape",
    title: "SQL escape",
    description: "Escape single quotes for SQL string literals.",
    category: "database",
    icon: "'",
  },
  {
    slug: "password-generator",
    title: "Password generator",
    description: "Cryptographically random passwords — length and charset.",
    category: "randomizers",
    icon: "🔑",
  },
  {
    slug: "passphrase-generator",
    title: "Passphrase generator",
    description: "Random word-style passphrases from a word list.",
    category: "randomizers",
    icon: "📝",
  },
  {
    slug: "pin-generator",
    title: "PIN generator",
    description: "Numeric PINs with secure randomness.",
    category: "randomizers",
    icon: "#",
  },
  {
    slug: "base32-encoder",
    title: "Base32 encoder",
    description: "Encode UTF-8 text to RFC 4648 Base32.",
    category: "base32",
    icon: "Ⓑ",
  },
  {
    slug: "base32-decoder",
    title: "Base32 decoder",
    description: "Decode Base32 to UTF-8 text.",
    category: "base32",
    icon: "Ⓑ",
  },
  {
    slug: "base32-to-hex",
    title: "Base32 to HEX",
    description: "Decode Base32 to hex string.",
    category: "base32",
    icon: "→",
  },
  {
    slug: "hex-to-base32",
    title: "HEX to Base32",
    description: "Encode hex bytes as Base32.",
    category: "base32",
    icon: "←",
  },
  {
    slug: "base58-encoder",
    title: "Base58 encoder",
    description: "Encode UTF-8 bytes as Base58.",
    category: "base58",
    icon: "₿",
  },
  {
    slug: "base58-decoder",
    title: "Base58 decoder",
    description: "Decode Base58 to UTF-8.",
    category: "base58",
    icon: "₿",
  },
  {
    slug: "base58-to-hex",
    title: "Base58 to HEX",
    description: "Decode Base58 to hex.",
    category: "base58",
    icon: "→",
  },
  {
    slug: "hex-to-base58",
    title: "HEX to Base58",
    description: "Encode hex as Base58.",
    category: "base58",
    icon: "←",
  },
  {
    slug: "base64-encoder",
    title: "Base64 encoder",
    description: "Encode UTF-8 text to Base64.",
    category: "base64",
    icon: "⊕",
  },
  {
    slug: "base64-decoder",
    title: "Base64 decoder",
    description: "Decode Base64 to UTF-8 text.",
    category: "base64",
    icon: "⊕",
  },
  {
    slug: "base64-to-hex",
    title: "Base64 to HEX",
    description: "Decode Base64 to hex bytes.",
    category: "base64",
    icon: "→",
  },
  {
    slug: "hex-to-base64",
    title: "HEX to Base64",
    description: "Encode hex as Base64.",
    category: "base64",
    icon: "←",
  },
  {
    slug: "base64-to-image",
    title: "Base64 to image",
    description: "Render a data URL / raw Base64 image in the browser.",
    category: "base64",
    icon: "🖼",
  },
  {
    slug: "image-to-base64",
    title: "Image to Base64",
    description: "Read a local image file to Base64 data URL.",
    category: "base64",
    icon: "📎",
  },
  {
    slug: "md5-hash-generator",
    title: "MD5 hash generator",
    description: "MD5 digest (crypto-js) — not for security.",
    category: "hash",
    icon: "⒨",
  },
  {
    slug: "sha1-hash-generator",
    title: "SHA-1 hash generator",
    description: "SHA-1 digest — legacy interoperability.",
    category: "hash",
    icon: "⒮",
  },
  {
    slug: "sha224-hash-generator",
    title: "SHA-224 hash generator",
    description: "SHA-224 digest.",
    category: "hash",
    icon: "⒯",
  },
  {
    slug: "sha256-hash-generator",
    title: "SHA-256 hash generator",
    description: "SHA-256 digest.",
    category: "hash",
    icon: "⒮",
  },
  {
    slug: "sha384-hash-generator",
    title: "SHA-384 hash generator",
    description: "SHA-384 digest.",
    category: "hash",
    icon: "⒮",
  },
  {
    slug: "sha512-hash-generator",
    title: "SHA-512 hash generator",
    description: "SHA-512 digest.",
    category: "hash",
    icon: "⒮",
  },
  {
    slug: "sha3-hash-generator",
    title: "SHA-3 hash generator",
    description: "SHA3-256 digest (crypto-js).",
    category: "hash",
    icon: "⒮",
  },
  {
    slug: "ripemd160-hash-generator",
    title: "RIPEMD-160 hash generator",
    description: "RIPEMD-160 digest.",
    category: "hash",
    icon: "Ⓡ",
  },
  {
    slug: "hmac-md5",
    title: "MD5 HMAC generator",
    description: "HMAC-MD5 hex.",
    category: "hmac",
    icon: "⒨",
  },
  {
    slug: "hmac-sha1",
    title: "SHA-1 HMAC generator",
    description: "HMAC-SHA1 hex.",
    category: "hmac",
    icon: "⒮",
  },
  {
    slug: "hmac-sha224",
    title: "SHA-224 HMAC generator",
    description: "HMAC-SHA224 hex.",
    category: "hmac",
    icon: "⒯",
  },
  {
    slug: "hmac-sha256",
    title: "SHA-256 HMAC generator",
    description: "HMAC-SHA256 hex.",
    category: "hmac",
    icon: "⒮",
  },
  {
    slug: "hmac-sha384",
    title: "SHA-384 HMAC generator",
    description: "HMAC-SHA384 hex.",
    category: "hmac",
    icon: "⒮",
  },
  {
    slug: "hmac-sha512",
    title: "SHA-512 HMAC generator",
    description: "HMAC-SHA512 hex.",
    category: "hmac",
    icon: "⒮",
  },
  {
    slug: "hmac-sha3",
    title: "SHA-3 HMAC generator",
    description: "HMAC-SHA3 hex.",
    category: "hmac",
    icon: "⒮",
  },
  {
    slug: "hmac-ripemd160",
    title: "RIPEMD-160 HMAC generator",
    description: "HMAC-RIPEMD160 hex.",
    category: "hmac",
    icon: "Ⓡ",
  },
  {
    slug: "bcrypt-generator",
    title: "Bcrypt generator",
    description: "Generate bcrypt hashes with configurable cost.",
    category: "bcrypt",
    icon: "⚿",
  },
  {
    slug: "bcrypt-checker",
    title: "Bcrypt checker",
    description: "Verify a password against a bcrypt hash.",
    category: "bcrypt",
    icon: "⚿",
  },
  {
    slug: "qr-to-text",
    title: "QR code to text",
    description: "Decode QR from an image file — processing stays in your browser.",
    category: "qrcode",
    icon: "▢",
  },
  {
    slug: "my-ip",
    title: "My IP",
    description: "Shows your public IP as seen by this site (server header).",
    category: "network",
    icon: "🌐",
  },
  {
    slug: "my-user-agent",
    title: "My user agent",
    description: "Display navigator.userAgent and platform hints.",
    category: "network",
    icon: "🧭",
  },
];
